# Generated by Django 3.0.6 on 2020-06-12 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200611_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='original_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CodeSnippet'),
        ),
    ]
